grid_search:
  parameters:
    global:
      compute_type:
        - "int8_float32"
        - "float32"
      model_type: 
        - "tiny.en"
        - "large-v3"
      beam_size: 
        - 3
        - 5
        - 7
      use_context: 
        - True
        - False
      confidence_based:
        - True
        - False
      num_workers:
        - 1
        - 2
        - 3
    confidence:
      confidence_limit: 
        - 0.6
        - 0.7
        - 0.8


experiment_setup:
  output_dir: "results/"
  num_trials: 1
  random_seed: 42
