name: Automatic testing

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out
      
      - name: Run tests
        id: run_tests
        run: |
          docker compose -f docker-test.yml up --build -d
          docker compose -f docker-test.yml exec backend pytest -v
        # REMOVE continue-on-error: true to ensure the step fails on errors

      - name: Write logs
        if: ${{ !success() }} # Write logs only if the test step failed
        run: |
          docker logs backend-backend-1
    
      - name: Stop containers
        if: always() # Ensure containers are stopped no matter what
        run: |
          docker compose -f docker-test.yml down
